---
### network properties
populations:
  - E
  - I

# number of neurons in populations
N:
  - 800
  - 200

# connection probability
p: 0.2

# ratio of inhibitory to excitatory weights
g: 5.0

# connection rule
connection_rule: fixed_indegree
# connection_rule: pairwise_bernoulli

neuron_type: iaf_psc_delta
# neuron_type: iaf_psc_exp

# multapses
multapses: False

### neuron properties
# membrane capacitance
C:
  val: 1.0
  unit: pF

# membrane time constant
tau_m:
  val: 20.0
  unit: ms

# refractory time
tau_r:
  val: 2.0
  unit: ms

# absolute reset potential
V_0_rel:
  val: 0.0
  unit: mV

# absolute threshold of membrane potential
V_th_rel:
  val: 15.0
  unit: mV

# resting membrane potential
E_L:
  val: 0.0
  unit: mV

# initial membrane voltage
V_m:
  val: 0.0
  unit: mV

### synapses
# synaptic time constant
tau_s:
  val: 0.0
  unit: ms

# delay connections
d:
  val: 1.0
  unit: ms

# delay distribution, options: none, gaussian (standard deviation is defined
# above), truncated_gaussian (standard deviation is defined above, truncation
# at zero)
delay_dist: none

# PSP amplitude
j:
  val: 0.8
  unit: mV

# wether to use Gaussian weights or not
gaussianize: True

# ratio of mean j used as standard deviation
j_std: 0.2

nu_ext:
  val:
    - 1017.73
    - 220.58
  unit: Hz

I_ext:
  val: 1.0
  unit: pA

...
